name: "Afvalwijzer: Validation And Formatting"

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: afvalwijzer-validation-and-formatting
  cancel-in-progress: false

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest validation
    steps:
      - uses: "actions/checkout@v6.0.1"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
      - uses: "actions/checkout@v6"
      - uses: "actions/setup-python@v6"
        with:
          python-version: "3.x"
      - run: python3 -m pip install ruff
      - run: ruff check --output-format github .

  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - uses: "actions/checkout@v6"
      - uses: "actions/setup-python@v6"
        with:
          python-version: "3.x"
      - run: |
          python3 -m pip install -r requirements
          python3 -m pip install pytest pytest-timeout pytest-cov
      - run: scripts/test
      - run: |
          scripts/coverage
          curl -sfSL https://codecov.io/bash | bash -
